services:
  ansible:
    build: .
    hostname: workspace
    volumes:
      - ./ansible:/ansible
      - homedir:/root

volumes:
  homedir:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-10.131.0.0/24}
