version: "3.5"

services:

  ansible:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    volumes:
      - ansible_homedir:/root
      - ./playbook.yml:/root/playbook.yml

volumes:
  ansible_homedir:
